python3 ft_cub_dbt.py \
  --rec-train ../data/n1_crops_dataset/n1_training_clean/n1_rec_train.rec --rec-train-idx ../data/n1_crops_dataset/n1_training_clean/n1_rec_train.idx \
  --rec-val ../data/n1_crops_dataset/n1_training_clean/n1_rec_val.rec --rec-val-idx ../data/n1_crops_dataset/n1_training_clean/n1_rec_val.idx \
  --model resnet50 --mode hybrid \
  --lr 0.05 --lr-mode cosine --num-epochs 10 --batch-size 16 --num-gpus 2 -j 12 --crop-ratio 0.875\
  --input-size 224\
  --nclasses 457\
  --num-training-samples 15777 \
  --warmup-epochs 0 --dtype float16 \
  --use-rec --no-wd --label-smoothing --last-gamma \
  --save-dir ../model/params_n1_training_clean_dbt \
  --export-model \
  --logging-file ../model/log/n1_training_clean_dbt.log 
